// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the videotask type in the database.
	Label = "video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicTaskID holds the string denoting the public_task_id field in the database.
	FieldPublicTaskID = "public_task_id"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldBillingModel holds the string denoting the billing_model field in the database.
	FieldBillingModel = "billing_model"
	// FieldModelMappingChain holds the string denoting the model_mapping_chain field in the database.
	FieldModelMappingChain = "model_mapping_chain"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProviderStatus holds the string denoting the provider_status field in the database.
	FieldProviderStatus = "provider_status"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldPromptHash holds the string denoting the prompt_hash field in the database.
	FieldPromptHash = "prompt_hash"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldRequestMetadata holds the string denoting the request_metadata field in the database.
	FieldRequestMetadata = "request_metadata"
	// FieldUpstreamBaseURL holds the string denoting the upstream_base_url field in the database.
	FieldUpstreamBaseURL = "upstream_base_url"
	// FieldUpstreamResponse holds the string denoting the upstream_response field in the database.
	FieldUpstreamResponse = "upstream_response"
	// FieldUpstreamResponseBody holds the string denoting the upstream_response_body field in the database.
	FieldUpstreamResponseBody = "upstream_response_body"
	// FieldResultURL holds the string denoting the result_url field in the database.
	FieldResultURL = "result_url"
	// FieldResultContentType holds the string denoting the result_content_type field in the database.
	FieldResultContentType = "result_content_type"
	// FieldResultMetadata holds the string denoting the result_metadata field in the database.
	FieldResultMetadata = "result_metadata"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldIdempotencyKeyHash holds the string denoting the idempotency_key_hash field in the database.
	FieldIdempotencyKeyHash = "idempotency_key_hash"
	// FieldUsageMetadata holds the string denoting the usage_metadata field in the database.
	FieldUsageMetadata = "usage_metadata"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldBilledUsd holds the string denoting the billed_usd field in the database.
	FieldBilledUsd = "billed_usd"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldNextPollAt holds the string denoting the next_poll_at field in the database.
	FieldNextPollAt = "next_poll_at"
	// FieldLastPolledAt holds the string denoting the last_polled_at field in the database.
	FieldLastPolledAt = "last_polled_at"
	// FieldLockedUntil holds the string denoting the locked_until field in the database.
	FieldLockedUntil = "locked_until"
	// FieldLockedBy holds the string denoting the locked_by field in the database.
	FieldLockedBy = "locked_by"
	// FieldPollAttempts holds the string denoting the poll_attempts field in the database.
	FieldPollAttempts = "poll_attempts"
	// FieldUserDeletedAt holds the string denoting the user_deleted_at field in the database.
	FieldUserDeletedAt = "user_deleted_at"
	// Table holds the table name of the videotask in the database.
	Table = "video_tasks"
)

// Columns holds all SQL columns for videotask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicTaskID,
	FieldUpstreamTaskID,
	FieldProvider,
	FieldPlatform,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldSubscriptionID,
	FieldAccountID,
	FieldChannelID,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldBillingModel,
	FieldModelMappingChain,
	FieldStatus,
	FieldProviderStatus,
	FieldProgress,
	FieldPrompt,
	FieldRequestHash,
	FieldPromptHash,
	FieldRequestBody,
	FieldRequestMetadata,
	FieldUpstreamBaseURL,
	FieldUpstreamResponse,
	FieldUpstreamResponseBody,
	FieldResultURL,
	FieldResultContentType,
	FieldResultMetadata,
	FieldErrorCode,
	FieldErrorMessage,
	FieldIdempotencyKey,
	FieldIdempotencyKeyHash,
	FieldUsageMetadata,
	FieldUsageLogID,
	FieldInputTokens,
	FieldOutputTokens,
	FieldBilledUsd,
	FieldSubmittedAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldExpiresAt,
	FieldNextPollAt,
	FieldLastPolledAt,
	FieldLockedUntil,
	FieldLockedBy,
	FieldPollAttempts,
	FieldUserDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicTaskIDValidator is a validator for the "public_task_id" field. It is called by the builders before save.
	PublicTaskIDValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// BillingModelValidator is a validator for the "billing_model" field. It is called by the builders before save.
	BillingModelValidator func(string) error
	// ModelMappingChainValidator is a validator for the "model_mapping_chain" field. It is called by the builders before save.
	ModelMappingChainValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ProviderStatusValidator is a validator for the "provider_status" field. It is called by the builders before save.
	ProviderStatusValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int
	// ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	ProgressValidator func(int) error
	// PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	PromptValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// PromptHashValidator is a validator for the "prompt_hash" field. It is called by the builders before save.
	PromptHashValidator func(string) error
	// DefaultRequestMetadata holds the default value on creation for the "request_metadata" field.
	DefaultRequestMetadata func() map[string]interface{}
	// UpstreamBaseURLValidator is a validator for the "upstream_base_url" field. It is called by the builders before save.
	UpstreamBaseURLValidator func(string) error
	// ResultURLValidator is a validator for the "result_url" field. It is called by the builders before save.
	ResultURLValidator func(string) error
	// ResultContentTypeValidator is a validator for the "result_content_type" field. It is called by the builders before save.
	ResultContentTypeValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	IdempotencyKeyHashValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultBilledUsd holds the default value on creation for the "billed_usd" field.
	DefaultBilledUsd float64
	// LockedByValidator is a validator for the "locked_by" field. It is called by the builders before save.
	LockedByValidator func(string) error
	// DefaultPollAttempts holds the default value on creation for the "poll_attempts" field.
	DefaultPollAttempts int
)

// OrderOption defines the ordering options for the VideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicTaskID orders the results by the public_task_id field.
func ByPublicTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicTaskID, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByBillingModel orders the results by the billing_model field.
func ByBillingModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingModel, opts...).ToFunc()
}

// ByModelMappingChain orders the results by the model_mapping_chain field.
func ByModelMappingChain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelMappingChain, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProviderStatus orders the results by the provider_status field.
func ByProviderStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderStatus, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByPromptHash orders the results by the prompt_hash field.
func ByPromptHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptHash, opts...).ToFunc()
}

// ByUpstreamBaseURL orders the results by the upstream_base_url field.
func ByUpstreamBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamBaseURL, opts...).ToFunc()
}

// ByResultURL orders the results by the result_url field.
func ByResultURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultURL, opts...).ToFunc()
}

// ByResultContentType orders the results by the result_content_type field.
func ByResultContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultContentType, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByIdempotencyKeyHash orders the results by the idempotency_key_hash field.
func ByIdempotencyKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKeyHash, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByBilledUsd orders the results by the billed_usd field.
func ByBilledUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBilledUsd, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByNextPollAt orders the results by the next_poll_at field.
func ByNextPollAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextPollAt, opts...).ToFunc()
}

// ByLastPolledAt orders the results by the last_polled_at field.
func ByLastPolledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPolledAt, opts...).ToFunc()
}

// ByLockedUntil orders the results by the locked_until field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByLockedBy orders the results by the locked_by field.
func ByLockedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedBy, opts...).ToFunc()
}

// ByPollAttempts orders the results by the poll_attempts field.
func ByPollAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollAttempts, opts...).ToFunc()
}

// ByUserDeletedAt orders the results by the user_deleted_at field.
func ByUserDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserDeletedAt, opts...).ToFunc()
}
