// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskUpdate is the builder for updating VideoTask entities.
type VideoTaskUpdate struct {
	config
	hooks    []Hook
	mutation *VideoTaskMutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdate) Where(ps ...predicate.VideoTask) *VideoTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdate) SetUpdatedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicTaskID sets the "public_task_id" field.
func (_u *VideoTaskUpdate) SetPublicTaskID(v string) *VideoTaskUpdate {
	_u.mutation.SetPublicTaskID(v)
	return _u
}

// SetNillablePublicTaskID sets the "public_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePublicTaskID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPublicTaskID(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdate) SetUpstreamTaskID(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdate) ClearUpstreamTaskID() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *VideoTaskUpdate) SetProvider(v string) *VideoTaskUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableProvider(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *VideoTaskUpdate) SetPlatform(v string) *VideoTaskUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePlatform(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdate) SetUserID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUserID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdate) AddUserID(v int64) *VideoTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdate) SetAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAPIKeyID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdate) AddAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdate) SetGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableGroupID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdate) AddGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *VideoTaskUpdate) SetSubscriptionID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSubscriptionID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *VideoTaskUpdate) AddSubscriptionID(v int64) *VideoTaskUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *VideoTaskUpdate) ClearSubscriptionID() *VideoTaskUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdate) SetAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAccountID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdate) AddAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *VideoTaskUpdate) SetChannelID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableChannelID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *VideoTaskUpdate) AddChannelID(v int64) *VideoTaskUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *VideoTaskUpdate) ClearChannelID() *VideoTaskUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *VideoTaskUpdate) SetRequestedModel(v string) *VideoTaskUpdate {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRequestedModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdate) SetUpstreamModel(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetBillingModel sets the "billing_model" field.
func (_u *VideoTaskUpdate) SetBillingModel(v string) *VideoTaskUpdate {
	_u.mutation.SetBillingModel(v)
	return _u
}

// SetNillableBillingModel sets the "billing_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillingModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillingModel(*v)
	}
	return _u
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (_u *VideoTaskUpdate) SetModelMappingChain(v string) *VideoTaskUpdate {
	_u.mutation.SetModelMappingChain(v)
	return _u
}

// SetNillableModelMappingChain sets the "model_mapping_chain" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableModelMappingChain(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetModelMappingChain(*v)
	}
	return _u
}

// ClearModelMappingChain clears the value of the "model_mapping_chain" field.
func (_u *VideoTaskUpdate) ClearModelMappingChain() *VideoTaskUpdate {
	_u.mutation.ClearModelMappingChain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdate) SetStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderStatus sets the "provider_status" field.
func (_u *VideoTaskUpdate) SetProviderStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetProviderStatus(v)
	return _u
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableProviderStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetProviderStatus(*v)
	}
	return _u
}

// ClearProviderStatus clears the value of the "provider_status" field.
func (_u *VideoTaskUpdate) ClearProviderStatus() *VideoTaskUpdate {
	_u.mutation.ClearProviderStatus()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *VideoTaskUpdate) SetProgress(v int) *VideoTaskUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableProgress(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *VideoTaskUpdate) AddProgress(v int) *VideoTaskUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *VideoTaskUpdate) SetPrompt(v string) *VideoTaskUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePrompt(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *VideoTaskUpdate) SetRequestHash(v string) *VideoTaskUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRequestHash(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *VideoTaskUpdate) SetPromptHash(v string) *VideoTaskUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePromptHash(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *VideoTaskUpdate) ClearPromptHash() *VideoTaskUpdate {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *VideoTaskUpdate) SetRequestBody(v []byte) *VideoTaskUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *VideoTaskUpdate) ClearRequestBody() *VideoTaskUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestMetadata sets the "request_metadata" field.
func (_u *VideoTaskUpdate) SetRequestMetadata(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetRequestMetadata(v)
	return _u
}

// SetUpstreamBaseURL sets the "upstream_base_url" field.
func (_u *VideoTaskUpdate) SetUpstreamBaseURL(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamBaseURL(v)
	return _u
}

// SetNillableUpstreamBaseURL sets the "upstream_base_url" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamBaseURL(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamBaseURL(*v)
	}
	return _u
}

// ClearUpstreamBaseURL clears the value of the "upstream_base_url" field.
func (_u *VideoTaskUpdate) ClearUpstreamBaseURL() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamBaseURL()
	return _u
}

// SetUpstreamResponse sets the "upstream_response" field.
func (_u *VideoTaskUpdate) SetUpstreamResponse(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetUpstreamResponse(v)
	return _u
}

// ClearUpstreamResponse clears the value of the "upstream_response" field.
func (_u *VideoTaskUpdate) ClearUpstreamResponse() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamResponse()
	return _u
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (_u *VideoTaskUpdate) SetUpstreamResponseBody(v []byte) *VideoTaskUpdate {
	_u.mutation.SetUpstreamResponseBody(v)
	return _u
}

// ClearUpstreamResponseBody clears the value of the "upstream_response_body" field.
func (_u *VideoTaskUpdate) ClearUpstreamResponseBody() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamResponseBody()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *VideoTaskUpdate) SetResultURL(v string) *VideoTaskUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultURL(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *VideoTaskUpdate) ClearResultURL() *VideoTaskUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *VideoTaskUpdate) SetResultContentType(v string) *VideoTaskUpdate {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultContentType(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *VideoTaskUpdate) ClearResultContentType() *VideoTaskUpdate {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetResultMetadata sets the "result_metadata" field.
func (_u *VideoTaskUpdate) SetResultMetadata(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetResultMetadata(v)
	return _u
}

// ClearResultMetadata clears the value of the "result_metadata" field.
func (_u *VideoTaskUpdate) ClearResultMetadata() *VideoTaskUpdate {
	_u.mutation.ClearResultMetadata()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *VideoTaskUpdate) SetErrorCode(v string) *VideoTaskUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableErrorCode(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *VideoTaskUpdate) ClearErrorCode() *VideoTaskUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *VideoTaskUpdate) SetErrorMessage(v string) *VideoTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableErrorMessage(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *VideoTaskUpdate) ClearErrorMessage() *VideoTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *VideoTaskUpdate) SetIdempotencyKey(v string) *VideoTaskUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableIdempotencyKey(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *VideoTaskUpdate) ClearIdempotencyKey() *VideoTaskUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *VideoTaskUpdate) SetIdempotencyKeyHash(v string) *VideoTaskUpdate {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableIdempotencyKeyHash(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// ClearIdempotencyKeyHash clears the value of the "idempotency_key_hash" field.
func (_u *VideoTaskUpdate) ClearIdempotencyKeyHash() *VideoTaskUpdate {
	_u.mutation.ClearIdempotencyKeyHash()
	return _u
}

// SetUsageMetadata sets the "usage_metadata" field.
func (_u *VideoTaskUpdate) SetUsageMetadata(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetUsageMetadata(v)
	return _u
}

// ClearUsageMetadata clears the value of the "usage_metadata" field.
func (_u *VideoTaskUpdate) ClearUsageMetadata() *VideoTaskUpdate {
	_u.mutation.ClearUsageMetadata()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *VideoTaskUpdate) SetUsageLogID(v int64) *VideoTaskUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUsageLogID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *VideoTaskUpdate) AddUsageLogID(v int64) *VideoTaskUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *VideoTaskUpdate) ClearUsageLogID() *VideoTaskUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *VideoTaskUpdate) SetInputTokens(v int) *VideoTaskUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableInputTokens(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *VideoTaskUpdate) AddInputTokens(v int) *VideoTaskUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *VideoTaskUpdate) SetOutputTokens(v int) *VideoTaskUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableOutputTokens(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *VideoTaskUpdate) AddOutputTokens(v int) *VideoTaskUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetBilledUsd sets the "billed_usd" field.
func (_u *VideoTaskUpdate) SetBilledUsd(v float64) *VideoTaskUpdate {
	_u.mutation.ResetBilledUsd()
	_u.mutation.SetBilledUsd(v)
	return _u
}

// SetNillableBilledUsd sets the "billed_usd" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBilledUsd(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetBilledUsd(*v)
	}
	return _u
}

// AddBilledUsd adds value to the "billed_usd" field.
func (_u *VideoTaskUpdate) AddBilledUsd(v float64) *VideoTaskUpdate {
	_u.mutation.AddBilledUsd(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *VideoTaskUpdate) SetSubmittedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableSubmittedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *VideoTaskUpdate) ClearSubmittedAt() *VideoTaskUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoTaskUpdate) SetStartedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStartedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoTaskUpdate) ClearStartedAt() *VideoTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VideoTaskUpdate) SetCompletedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableCompletedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VideoTaskUpdate) ClearCompletedAt() *VideoTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VideoTaskUpdate) SetExpiresAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableExpiresAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *VideoTaskUpdate) ClearExpiresAt() *VideoTaskUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdate) SetNextPollAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// ClearNextPollAt clears the value of the "next_poll_at" field.
func (_u *VideoTaskUpdate) ClearNextPollAt() *VideoTaskUpdate {
	_u.mutation.ClearNextPollAt()
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *VideoTaskUpdate) SetLastPolledAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLastPolledAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *VideoTaskUpdate) ClearLastPolledAt() *VideoTaskUpdate {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *VideoTaskUpdate) SetLockedUntil(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLockedUntil(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *VideoTaskUpdate) ClearLockedUntil() *VideoTaskUpdate {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *VideoTaskUpdate) SetLockedBy(v string) *VideoTaskUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableLockedBy(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *VideoTaskUpdate) ClearLockedBy() *VideoTaskUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdate) SetPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePollAttempts(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdate) AddPollAttempts(v int) *VideoTaskUpdate {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (_u *VideoTaskUpdate) SetUserDeletedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetUserDeletedAt(v)
	return _u
}

// SetNillableUserDeletedAt sets the "user_deleted_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUserDeletedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetUserDeletedAt(*v)
	}
	return _u
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (_u *VideoTaskUpdate) ClearUserDeletedAt() *VideoTaskUpdate {
	_u.mutation.ClearUserDeletedAt()
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdate) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdate) check() error {
	if v, ok := _u.mutation.PublicTaskID(); ok {
		if err := videotask.PublicTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "public_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.public_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := videotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := videotask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "VideoTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := videotask.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingModel(); ok {
		if err := videotask.BillingModelValidator(v); err != nil {
			return &ValidationError{Name: "billing_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelMappingChain(); ok {
		if err := videotask.ModelMappingChainValidator(v); err != nil {
			return &ValidationError{Name: "model_mapping_chain", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model_mapping_chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderStatus(); ok {
		if err := videotask.ProviderStatusValidator(v); err != nil {
			return &ValidationError{Name: "provider_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := videotask.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "VideoTask.progress": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := videotask.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "VideoTask.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := videotask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := videotask.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamBaseURL(); ok {
		if err := videotask.UpstreamBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "upstream_base_url", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultURL(); ok {
		if err := videotask.ResultURLValidator(v); err != nil {
			return &ValidationError{Name: "result_url", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := videotask.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := videotask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoTask.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := videotask.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := videotask.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LockedBy(); ok {
		if err := videotask.LockedByValidator(v); err != nil {
			return &ValidationError{Name: "locked_by", err: fmt.Errorf(`ent: validator failed for field "VideoTask.locked_by": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicTaskID(); ok {
		_spec.SetField(videotask.FieldPublicTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(videotask.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(videotask.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(videotask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(videotask.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(videotask.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(videotask.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(videotask.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingModel(); ok {
		_spec.SetField(videotask.FieldBillingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelMappingChain(); ok {
		_spec.SetField(videotask.FieldModelMappingChain, field.TypeString, value)
	}
	if _u.mutation.ModelMappingChainCleared() {
		_spec.ClearField(videotask.FieldModelMappingChain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderStatus(); ok {
		_spec.SetField(videotask.FieldProviderStatus, field.TypeString, value)
	}
	if _u.mutation.ProviderStatusCleared() {
		_spec.ClearField(videotask.FieldProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(videotask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(videotask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(videotask.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(videotask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(videotask.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(videotask.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(videotask.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(videotask.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestMetadata(); ok {
		_spec.SetField(videotask.FieldRequestMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpstreamBaseURL(); ok {
		_spec.SetField(videotask.FieldUpstreamBaseURL, field.TypeString, value)
	}
	if _u.mutation.UpstreamBaseURLCleared() {
		_spec.ClearField(videotask.FieldUpstreamBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamResponse(); ok {
		_spec.SetField(videotask.FieldUpstreamResponse, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamResponseCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponse, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseBody(); ok {
		_spec.SetField(videotask.FieldUpstreamResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.UpstreamResponseBodyCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(videotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(videotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(videotask.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(videotask.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ResultMetadata(); ok {
		_spec.SetField(videotask.FieldResultMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ResultMetadataCleared() {
		_spec.ClearField(videotask.FieldResultMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(videotask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(videotask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(videotask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(videotask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(videotask.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(videotask.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(videotask.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyHashCleared() {
		_spec.ClearField(videotask.FieldIdempotencyKeyHash, field.TypeString)
	}
	if value, ok := _u.mutation.UsageMetadata(); ok {
		_spec.SetField(videotask.FieldUsageMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UsageMetadataCleared() {
		_spec.ClearField(videotask.FieldUsageMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(videotask.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(videotask.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(videotask.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(videotask.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(videotask.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(videotask.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(videotask.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BilledUsd(); ok {
		_spec.SetField(videotask.FieldBilledUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledUsd(); ok {
		_spec.AddField(videotask.FieldBilledUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(videotask.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(videotask.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(videotask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(videotask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(videotask.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(videotask.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if _u.mutation.NextPollAtCleared() {
		_spec.ClearField(videotask.FieldNextPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(videotask.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(videotask.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(videotask.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(videotask.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(videotask.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(videotask.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserDeletedAt(); ok {
		_spec.SetField(videotask.FieldUserDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserDeletedAtCleared() {
		_spec.ClearField(videotask.FieldUserDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoTaskUpdateOne is the builder for updating a single VideoTask entity.
type VideoTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdateOne) SetUpdatedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicTaskID sets the "public_task_id" field.
func (_u *VideoTaskUpdateOne) SetPublicTaskID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPublicTaskID(v)
	return _u
}

// SetNillablePublicTaskID sets the "public_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePublicTaskID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPublicTaskID(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) SetUpstreamTaskID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamTaskID() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *VideoTaskUpdateOne) SetProvider(v string) *VideoTaskUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableProvider(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *VideoTaskUpdateOne) SetPlatform(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePlatform(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdateOne) SetUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUserID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoTaskUpdateOne) AddUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdateOne) SetAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAPIKeyID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *VideoTaskUpdateOne) AddAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdateOne) SetGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableGroupID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoTaskUpdateOne) AddGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *VideoTaskUpdateOne) SetSubscriptionID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSubscriptionID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *VideoTaskUpdateOne) AddSubscriptionID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *VideoTaskUpdateOne) ClearSubscriptionID() *VideoTaskUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdateOne) SetAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAccountID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoTaskUpdateOne) AddAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *VideoTaskUpdateOne) SetChannelID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableChannelID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *VideoTaskUpdateOne) AddChannelID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *VideoTaskUpdateOne) ClearChannelID() *VideoTaskUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *VideoTaskUpdateOne) SetRequestedModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRequestedModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdateOne) SetUpstreamModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetBillingModel sets the "billing_model" field.
func (_u *VideoTaskUpdateOne) SetBillingModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetBillingModel(v)
	return _u
}

// SetNillableBillingModel sets the "billing_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillingModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillingModel(*v)
	}
	return _u
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (_u *VideoTaskUpdateOne) SetModelMappingChain(v string) *VideoTaskUpdateOne {
	_u.mutation.SetModelMappingChain(v)
	return _u
}

// SetNillableModelMappingChain sets the "model_mapping_chain" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableModelMappingChain(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetModelMappingChain(*v)
	}
	return _u
}

// ClearModelMappingChain clears the value of the "model_mapping_chain" field.
func (_u *VideoTaskUpdateOne) ClearModelMappingChain() *VideoTaskUpdateOne {
	_u.mutation.ClearModelMappingChain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdateOne) SetStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProviderStatus sets the "provider_status" field.
func (_u *VideoTaskUpdateOne) SetProviderStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetProviderStatus(v)
	return _u
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableProviderStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetProviderStatus(*v)
	}
	return _u
}

// ClearProviderStatus clears the value of the "provider_status" field.
func (_u *VideoTaskUpdateOne) ClearProviderStatus() *VideoTaskUpdateOne {
	_u.mutation.ClearProviderStatus()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *VideoTaskUpdateOne) SetProgress(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableProgress(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *VideoTaskUpdateOne) AddProgress(v int) *VideoTaskUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *VideoTaskUpdateOne) SetPrompt(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePrompt(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *VideoTaskUpdateOne) SetRequestHash(v string) *VideoTaskUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRequestHash(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *VideoTaskUpdateOne) SetPromptHash(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePromptHash(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *VideoTaskUpdateOne) ClearPromptHash() *VideoTaskUpdateOne {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *VideoTaskUpdateOne) SetRequestBody(v []byte) *VideoTaskUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *VideoTaskUpdateOne) ClearRequestBody() *VideoTaskUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestMetadata sets the "request_metadata" field.
func (_u *VideoTaskUpdateOne) SetRequestMetadata(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetRequestMetadata(v)
	return _u
}

// SetUpstreamBaseURL sets the "upstream_base_url" field.
func (_u *VideoTaskUpdateOne) SetUpstreamBaseURL(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamBaseURL(v)
	return _u
}

// SetNillableUpstreamBaseURL sets the "upstream_base_url" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamBaseURL(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamBaseURL(*v)
	}
	return _u
}

// ClearUpstreamBaseURL clears the value of the "upstream_base_url" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamBaseURL() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamBaseURL()
	return _u
}

// SetUpstreamResponse sets the "upstream_response" field.
func (_u *VideoTaskUpdateOne) SetUpstreamResponse(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamResponse(v)
	return _u
}

// ClearUpstreamResponse clears the value of the "upstream_response" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamResponse() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamResponse()
	return _u
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (_u *VideoTaskUpdateOne) SetUpstreamResponseBody(v []byte) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamResponseBody(v)
	return _u
}

// ClearUpstreamResponseBody clears the value of the "upstream_response_body" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamResponseBody() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamResponseBody()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *VideoTaskUpdateOne) SetResultURL(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultURL(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *VideoTaskUpdateOne) ClearResultURL() *VideoTaskUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *VideoTaskUpdateOne) SetResultContentType(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultContentType(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *VideoTaskUpdateOne) ClearResultContentType() *VideoTaskUpdateOne {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetResultMetadata sets the "result_metadata" field.
func (_u *VideoTaskUpdateOne) SetResultMetadata(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetResultMetadata(v)
	return _u
}

// ClearResultMetadata clears the value of the "result_metadata" field.
func (_u *VideoTaskUpdateOne) ClearResultMetadata() *VideoTaskUpdateOne {
	_u.mutation.ClearResultMetadata()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *VideoTaskUpdateOne) SetErrorCode(v string) *VideoTaskUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableErrorCode(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *VideoTaskUpdateOne) ClearErrorCode() *VideoTaskUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *VideoTaskUpdateOne) SetErrorMessage(v string) *VideoTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableErrorMessage(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *VideoTaskUpdateOne) ClearErrorMessage() *VideoTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *VideoTaskUpdateOne) SetIdempotencyKey(v string) *VideoTaskUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableIdempotencyKey(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *VideoTaskUpdateOne) ClearIdempotencyKey() *VideoTaskUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *VideoTaskUpdateOne) SetIdempotencyKeyHash(v string) *VideoTaskUpdateOne {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableIdempotencyKeyHash(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// ClearIdempotencyKeyHash clears the value of the "idempotency_key_hash" field.
func (_u *VideoTaskUpdateOne) ClearIdempotencyKeyHash() *VideoTaskUpdateOne {
	_u.mutation.ClearIdempotencyKeyHash()
	return _u
}

// SetUsageMetadata sets the "usage_metadata" field.
func (_u *VideoTaskUpdateOne) SetUsageMetadata(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetUsageMetadata(v)
	return _u
}

// ClearUsageMetadata clears the value of the "usage_metadata" field.
func (_u *VideoTaskUpdateOne) ClearUsageMetadata() *VideoTaskUpdateOne {
	_u.mutation.ClearUsageMetadata()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *VideoTaskUpdateOne) SetUsageLogID(v int64) *VideoTaskUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUsageLogID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *VideoTaskUpdateOne) AddUsageLogID(v int64) *VideoTaskUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *VideoTaskUpdateOne) ClearUsageLogID() *VideoTaskUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *VideoTaskUpdateOne) SetInputTokens(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableInputTokens(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *VideoTaskUpdateOne) AddInputTokens(v int) *VideoTaskUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *VideoTaskUpdateOne) SetOutputTokens(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableOutputTokens(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *VideoTaskUpdateOne) AddOutputTokens(v int) *VideoTaskUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetBilledUsd sets the "billed_usd" field.
func (_u *VideoTaskUpdateOne) SetBilledUsd(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetBilledUsd()
	_u.mutation.SetBilledUsd(v)
	return _u
}

// SetNillableBilledUsd sets the "billed_usd" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBilledUsd(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBilledUsd(*v)
	}
	return _u
}

// AddBilledUsd adds value to the "billed_usd" field.
func (_u *VideoTaskUpdateOne) AddBilledUsd(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddBilledUsd(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *VideoTaskUpdateOne) SetSubmittedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableSubmittedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *VideoTaskUpdateOne) ClearSubmittedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoTaskUpdateOne) SetStartedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStartedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoTaskUpdateOne) ClearStartedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VideoTaskUpdateOne) SetCompletedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VideoTaskUpdateOne) ClearCompletedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VideoTaskUpdateOne) SetExpiresAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableExpiresAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *VideoTaskUpdateOne) ClearExpiresAt() *VideoTaskUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetNextPollAt sets the "next_poll_at" field.
func (_u *VideoTaskUpdateOne) SetNextPollAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetNextPollAt(v)
	return _u
}

// SetNillableNextPollAt sets the "next_poll_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableNextPollAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetNextPollAt(*v)
	}
	return _u
}

// ClearNextPollAt clears the value of the "next_poll_at" field.
func (_u *VideoTaskUpdateOne) ClearNextPollAt() *VideoTaskUpdateOne {
	_u.mutation.ClearNextPollAt()
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *VideoTaskUpdateOne) SetLastPolledAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLastPolledAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *VideoTaskUpdateOne) ClearLastPolledAt() *VideoTaskUpdateOne {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// SetLockedUntil sets the "locked_until" field.
func (_u *VideoTaskUpdateOne) SetLockedUntil(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetLockedUntil(v)
	return _u
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLockedUntil(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLockedUntil(*v)
	}
	return _u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (_u *VideoTaskUpdateOne) ClearLockedUntil() *VideoTaskUpdateOne {
	_u.mutation.ClearLockedUntil()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *VideoTaskUpdateOne) SetLockedBy(v string) *VideoTaskUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableLockedBy(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *VideoTaskUpdateOne) ClearLockedBy() *VideoTaskUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) SetPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePollAttempts(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *VideoTaskUpdateOne) AddPollAttempts(v int) *VideoTaskUpdateOne {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (_u *VideoTaskUpdateOne) SetUserDeletedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetUserDeletedAt(v)
	return _u
}

// SetNillableUserDeletedAt sets the "user_deleted_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUserDeletedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUserDeletedAt(*v)
	}
	return _u
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (_u *VideoTaskUpdateOne) ClearUserDeletedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearUserDeletedAt()
	return _u
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdateOne) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdateOne) Where(ps ...predicate.VideoTask) *VideoTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoTaskUpdateOne) Select(field string, fields ...string) *VideoTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoTask entity.
func (_u *VideoTaskUpdateOne) Save(ctx context.Context) (*VideoTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) SaveX(ctx context.Context) *VideoTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdateOne) check() error {
	if v, ok := _u.mutation.PublicTaskID(); ok {
		if err := videotask.PublicTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "public_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.public_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := videotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := videotask.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "VideoTask.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := videotask.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingModel(); ok {
		if err := videotask.BillingModelValidator(v); err != nil {
			return &ValidationError{Name: "billing_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.billing_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelMappingChain(); ok {
		if err := videotask.ModelMappingChainValidator(v); err != nil {
			return &ValidationError{Name: "model_mapping_chain", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model_mapping_chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderStatus(); ok {
		if err := videotask.ProviderStatusValidator(v); err != nil {
			return &ValidationError{Name: "provider_status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := videotask.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "VideoTask.progress": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := videotask.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "VideoTask.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := videotask.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := videotask.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamBaseURL(); ok {
		if err := videotask.UpstreamBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "upstream_base_url", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultURL(); ok {
		if err := videotask.ResultURLValidator(v); err != nil {
			return &ValidationError{Name: "result_url", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := videotask.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "VideoTask.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := videotask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoTask.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := videotask.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := videotask.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "VideoTask.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LockedBy(); ok {
		if err := videotask.LockedByValidator(v); err != nil {
			return &ValidationError{Name: "locked_by", err: fmt.Errorf(`ent: validator failed for field "VideoTask.locked_by": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoTaskUpdateOne) sqlSave(ctx context.Context) (_node *VideoTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotask.FieldID)
		for _, f := range fields {
			if !videotask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videotask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicTaskID(); ok {
		_spec.SetField(videotask.FieldPublicTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(videotask.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(videotask.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videotask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(videotask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videotask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(videotask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(videotask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videotask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(videotask.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(videotask.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(videotask.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(videotask.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingModel(); ok {
		_spec.SetField(videotask.FieldBillingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelMappingChain(); ok {
		_spec.SetField(videotask.FieldModelMappingChain, field.TypeString, value)
	}
	if _u.mutation.ModelMappingChainCleared() {
		_spec.ClearField(videotask.FieldModelMappingChain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderStatus(); ok {
		_spec.SetField(videotask.FieldProviderStatus, field.TypeString, value)
	}
	if _u.mutation.ProviderStatusCleared() {
		_spec.ClearField(videotask.FieldProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(videotask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(videotask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(videotask.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(videotask.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(videotask.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(videotask.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(videotask.FieldRequestBody, field.TypeBytes, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(videotask.FieldRequestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.RequestMetadata(); ok {
		_spec.SetField(videotask.FieldRequestMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpstreamBaseURL(); ok {
		_spec.SetField(videotask.FieldUpstreamBaseURL, field.TypeString, value)
	}
	if _u.mutation.UpstreamBaseURLCleared() {
		_spec.ClearField(videotask.FieldUpstreamBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamResponse(); ok {
		_spec.SetField(videotask.FieldUpstreamResponse, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamResponseCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponse, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseBody(); ok {
		_spec.SetField(videotask.FieldUpstreamResponseBody, field.TypeBytes, value)
	}
	if _u.mutation.UpstreamResponseBodyCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponseBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(videotask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(videotask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(videotask.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(videotask.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ResultMetadata(); ok {
		_spec.SetField(videotask.FieldResultMetadata, field.TypeJSON, value)
	}
	if _u.mutation.ResultMetadataCleared() {
		_spec.ClearField(videotask.FieldResultMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(videotask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(videotask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(videotask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(videotask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(videotask.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(videotask.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(videotask.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyHashCleared() {
		_spec.ClearField(videotask.FieldIdempotencyKeyHash, field.TypeString)
	}
	if value, ok := _u.mutation.UsageMetadata(); ok {
		_spec.SetField(videotask.FieldUsageMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UsageMetadataCleared() {
		_spec.ClearField(videotask.FieldUsageMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(videotask.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(videotask.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(videotask.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(videotask.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(videotask.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(videotask.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(videotask.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BilledUsd(); ok {
		_spec.SetField(videotask.FieldBilledUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledUsd(); ok {
		_spec.AddField(videotask.FieldBilledUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(videotask.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(videotask.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videotask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videotask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(videotask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(videotask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(videotask.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(videotask.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextPollAt(); ok {
		_spec.SetField(videotask.FieldNextPollAt, field.TypeTime, value)
	}
	if _u.mutation.NextPollAtCleared() {
		_spec.ClearField(videotask.FieldNextPollAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(videotask.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(videotask.FieldLastPolledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedUntil(); ok {
		_spec.SetField(videotask.FieldLockedUntil, field.TypeTime, value)
	}
	if _u.mutation.LockedUntilCleared() {
		_spec.ClearField(videotask.FieldLockedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(videotask.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(videotask.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(videotask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserDeletedAt(); ok {
		_spec.SetField(videotask.FieldUserDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserDeletedAtCleared() {
		_spec.ClearField(videotask.FieldUserDeletedAt, field.TypeTime)
	}
	_node = &VideoTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
