// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTask is the model entity for the VideoTask schema.
type VideoTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicTaskID holds the value of the "public_task_id" field.
	PublicTaskID string `json:"public_task_id,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID *int64 `json:"channel_id,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// BillingModel holds the value of the "billing_model" field.
	BillingModel string `json:"billing_model,omitempty"`
	// ModelMappingChain holds the value of the "model_mapping_chain" field.
	ModelMappingChain *string `json:"model_mapping_chain,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ProviderStatus holds the value of the "provider_status" field.
	ProviderStatus *string `json:"provider_status,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int `json:"progress,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// PromptHash holds the value of the "prompt_hash" field.
	PromptHash *string `json:"prompt_hash,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody *[]byte `json:"request_body,omitempty"`
	// RequestMetadata holds the value of the "request_metadata" field.
	RequestMetadata map[string]interface{} `json:"request_metadata,omitempty"`
	// UpstreamBaseURL holds the value of the "upstream_base_url" field.
	UpstreamBaseURL *string `json:"upstream_base_url,omitempty"`
	// UpstreamResponse holds the value of the "upstream_response" field.
	UpstreamResponse map[string]interface{} `json:"upstream_response,omitempty"`
	// UpstreamResponseBody holds the value of the "upstream_response_body" field.
	UpstreamResponseBody *[]byte `json:"upstream_response_body,omitempty"`
	// ResultURL holds the value of the "result_url" field.
	ResultURL *string `json:"result_url,omitempty"`
	// ResultContentType holds the value of the "result_content_type" field.
	ResultContentType *string `json:"result_content_type,omitempty"`
	// ResultMetadata holds the value of the "result_metadata" field.
	ResultMetadata map[string]interface{} `json:"result_metadata,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// IdempotencyKeyHash holds the value of the "idempotency_key_hash" field.
	IdempotencyKeyHash *string `json:"idempotency_key_hash,omitempty"`
	// UsageMetadata holds the value of the "usage_metadata" field.
	UsageMetadata map[string]interface{} `json:"usage_metadata,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// BilledUsd holds the value of the "billed_usd" field.
	BilledUsd float64 `json:"billed_usd,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// NextPollAt holds the value of the "next_poll_at" field.
	NextPollAt *time.Time `json:"next_poll_at,omitempty"`
	// LastPolledAt holds the value of the "last_polled_at" field.
	LastPolledAt *time.Time `json:"last_polled_at,omitempty"`
	// LockedUntil holds the value of the "locked_until" field.
	LockedUntil *time.Time `json:"locked_until,omitempty"`
	// LockedBy holds the value of the "locked_by" field.
	LockedBy *string `json:"locked_by,omitempty"`
	// PollAttempts holds the value of the "poll_attempts" field.
	PollAttempts int `json:"poll_attempts,omitempty"`
	// UserDeletedAt holds the value of the "user_deleted_at" field.
	UserDeletedAt *time.Time `json:"user_deleted_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videotask.FieldRequestBody, videotask.FieldRequestMetadata, videotask.FieldUpstreamResponse, videotask.FieldUpstreamResponseBody, videotask.FieldResultMetadata, videotask.FieldUsageMetadata:
			values[i] = new([]byte)
		case videotask.FieldBilledUsd:
			values[i] = new(sql.NullFloat64)
		case videotask.FieldID, videotask.FieldUserID, videotask.FieldAPIKeyID, videotask.FieldGroupID, videotask.FieldSubscriptionID, videotask.FieldAccountID, videotask.FieldChannelID, videotask.FieldProgress, videotask.FieldUsageLogID, videotask.FieldInputTokens, videotask.FieldOutputTokens, videotask.FieldPollAttempts:
			values[i] = new(sql.NullInt64)
		case videotask.FieldPublicTaskID, videotask.FieldUpstreamTaskID, videotask.FieldProvider, videotask.FieldPlatform, videotask.FieldRequestedModel, videotask.FieldUpstreamModel, videotask.FieldBillingModel, videotask.FieldModelMappingChain, videotask.FieldStatus, videotask.FieldProviderStatus, videotask.FieldPrompt, videotask.FieldRequestHash, videotask.FieldPromptHash, videotask.FieldUpstreamBaseURL, videotask.FieldResultURL, videotask.FieldResultContentType, videotask.FieldErrorCode, videotask.FieldErrorMessage, videotask.FieldIdempotencyKey, videotask.FieldIdempotencyKeyHash, videotask.FieldLockedBy:
			values[i] = new(sql.NullString)
		case videotask.FieldCreatedAt, videotask.FieldUpdatedAt, videotask.FieldSubmittedAt, videotask.FieldStartedAt, videotask.FieldCompletedAt, videotask.FieldExpiresAt, videotask.FieldNextPollAt, videotask.FieldLastPolledAt, videotask.FieldLockedUntil, videotask.FieldUserDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoTask fields.
func (_m *VideoTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videotask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videotask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videotask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videotask.FieldPublicTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_task_id", values[i])
			} else if value.Valid {
				_m.PublicTaskID = value.String
			}
		case videotask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case videotask.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case videotask.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case videotask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case videotask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case videotask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case videotask.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case videotask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case videotask.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case videotask.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case videotask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case videotask.FieldBillingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_model", values[i])
			} else if value.Valid {
				_m.BillingModel = value.String
			}
		case videotask.FieldModelMappingChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_mapping_chain", values[i])
			} else if value.Valid {
				_m.ModelMappingChain = new(string)
				*_m.ModelMappingChain = value.String
			}
		case videotask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videotask.FieldProviderStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_status", values[i])
			} else if value.Valid {
				_m.ProviderStatus = new(string)
				*_m.ProviderStatus = value.String
			}
		case videotask.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case videotask.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case videotask.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case videotask.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = new(string)
				*_m.PromptHash = value.String
			}
		case videotask.FieldRequestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value != nil {
				_m.RequestBody = value
			}
		case videotask.FieldRequestMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestMetadata); err != nil {
					return fmt.Errorf("unmarshal field request_metadata: %w", err)
				}
			}
		case videotask.FieldUpstreamBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_base_url", values[i])
			} else if value.Valid {
				_m.UpstreamBaseURL = new(string)
				*_m.UpstreamBaseURL = value.String
			}
		case videotask.FieldUpstreamResponse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamResponse); err != nil {
					return fmt.Errorf("unmarshal field upstream_response: %w", err)
				}
			}
		case videotask.FieldUpstreamResponseBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_body", values[i])
			} else if value != nil {
				_m.UpstreamResponseBody = value
			}
		case videotask.FieldResultURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_url", values[i])
			} else if value.Valid {
				_m.ResultURL = new(string)
				*_m.ResultURL = value.String
			}
		case videotask.FieldResultContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_content_type", values[i])
			} else if value.Valid {
				_m.ResultContentType = new(string)
				*_m.ResultContentType = value.String
			}
		case videotask.FieldResultMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultMetadata); err != nil {
					return fmt.Errorf("unmarshal field result_metadata: %w", err)
				}
			}
		case videotask.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case videotask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case videotask.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case videotask.FieldIdempotencyKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key_hash", values[i])
			} else if value.Valid {
				_m.IdempotencyKeyHash = new(string)
				*_m.IdempotencyKeyHash = value.String
			}
		case videotask.FieldUsageMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field usage_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UsageMetadata); err != nil {
					return fmt.Errorf("unmarshal field usage_metadata: %w", err)
				}
			}
		case videotask.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case videotask.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case videotask.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case videotask.FieldBilledUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field billed_usd", values[i])
			} else if value.Valid {
				_m.BilledUsd = value.Float64
			}
		case videotask.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case videotask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case videotask.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case videotask.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case videotask.FieldNextPollAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_poll_at", values[i])
			} else if value.Valid {
				_m.NextPollAt = new(time.Time)
				*_m.NextPollAt = value.Time
			}
		case videotask.FieldLastPolledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_polled_at", values[i])
			} else if value.Valid {
				_m.LastPolledAt = new(time.Time)
				*_m.LastPolledAt = value.Time
			}
		case videotask.FieldLockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_until", values[i])
			} else if value.Valid {
				_m.LockedUntil = new(time.Time)
				*_m.LockedUntil = value.Time
			}
		case videotask.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = new(string)
				*_m.LockedBy = value.String
			}
		case videotask.FieldPollAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_attempts", values[i])
			} else if value.Valid {
				_m.PollAttempts = int(value.Int64)
			}
		case videotask.FieldUserDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field user_deleted_at", values[i])
			} else if value.Valid {
				_m.UserDeletedAt = new(time.Time)
				*_m.UserDeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoTask.
// This includes values selected through modifiers, order, etc.
func (_m *VideoTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoTask.
// Note that you need to call VideoTask.Unwrap() before calling this method if this VideoTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoTask) Update() *VideoTaskUpdateOne {
	return NewVideoTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoTask) Unwrap() *VideoTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoTask) String() string {
	var builder strings.Builder
	builder.WriteString("VideoTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_task_id=")
	builder.WriteString(_m.PublicTaskID)
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("billing_model=")
	builder.WriteString(_m.BillingModel)
	builder.WriteString(", ")
	if v := _m.ModelMappingChain; v != nil {
		builder.WriteString("model_mapping_chain=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ProviderStatus; v != nil {
		builder.WriteString("provider_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	if v := _m.PromptHash; v != nil {
		builder.WriteString("prompt_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestBody; v != nil {
		builder.WriteString("request_body=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestMetadata))
	builder.WriteString(", ")
	if v := _m.UpstreamBaseURL; v != nil {
		builder.WriteString("upstream_base_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_response=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamResponse))
	builder.WriteString(", ")
	if v := _m.UpstreamResponseBody; v != nil {
		builder.WriteString("upstream_response_body=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResultURL; v != nil {
		builder.WriteString("result_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultContentType; v != nil {
		builder.WriteString("result_content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("result_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultMetadata))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdempotencyKeyHash; v != nil {
		builder.WriteString("idempotency_key_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("usage_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageMetadata))
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("billed_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.BilledUsd))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextPollAt; v != nil {
		builder.WriteString("next_poll_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastPolledAt; v != nil {
		builder.WriteString("last_polled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LockedUntil; v != nil {
		builder.WriteString("locked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LockedBy; v != nil {
		builder.WriteString("locked_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("poll_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollAttempts))
	builder.WriteString(", ")
	if v := _m.UserDeletedAt; v != nil {
		builder.WriteString("user_deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VideoTasks is a parsable slice of VideoTask.
type VideoTasks []*VideoTask
